/** Mirrors backend/app/schemas/patch.py */

export type PatchStatus = 'QUEUED' | 'RUNNING' | 'PROPOSED' | 'FAILED'

/** Still working — the UI polls while one of these is true. */
export const ACTIVE_PATCH_STATUSES: PatchStatus[] = ['QUEUED', 'RUNNING']

export type ValidationStatus = 'QUEUED' | 'RUNNING' | 'PASSED' | 'REJECTED' | 'FAILED'

export const ACTIVE_VALIDATION_STATUSES: ValidationStatus[] = ['QUEUED', 'RUNNING']

/** "skipped" is a real answer: it means this was not checked, not that it was fine. */
export type CheckOutcome = 'passed' | 'failed' | 'skipped'

/** One thing the re-scan tested, and how it came out. */
export interface ValidationCheck {
  key: string
  outcome: CheckOutcome
  detail: string
}

/** Something the patched copy has that the original code did not. */
export interface NewFinding {
  rule_id: string
  title: string
  severity: string
  file_path: string
  line: number
}

/**
 * One attempt to check a proposed change by applying it to a throwaway copy
 * and scanning again.
 *
 * PASSED and REJECTED are verdicts. FAILED is not one — it means the check
 * could not be made (the stored code moved, say) and says nothing about the
 * change itself.
 */
export interface PatchValidation {
  id: number
  status: ValidationStatus
  attempts: number
  checks: ValidationCheck[]
  findings_before: number | null
  findings_after: number | null
  /** Other findings the change happened to remove. Reported, not rewarded. */
  also_resolved: number
  new_findings: NewFinding[]
  duration_ms: number | null
  error_message: string | null
  created_at: string
  finished_at: string | null
}

/** What each check is called on screen. Unknown keys fall back to the key. */
export const CHECK_LABELS: Record<string, string> = {
  target_resolved: 'The finding is no longer detected',
  no_new_findings: 'Nothing new is detected',
  not_a_deletion: 'The code was replaced, not removed',
  still_parses: 'The file still parses',
}

/**
 * A proposed change to the code a finding points at.
 *
 * There is no 'APPLIED'. A patch is a proposal, and `validated` says only that
 * its most recent re-scan passed: the finding is no longer detected, nothing
 * new is, and the change is not a deletion. It does not say the program still
 * behaves the same, and it does not mean anything on disk changed.
 */
export interface Patch {
  id: number
  finding_id: number
  status: PatchStatus
  attempts: number

  /** A unified diff, generated by the server from before/after — not by the model. */
  diff: string | null
  rationale: string | null
  file_path: string | null
  first_line: number | null
  last_line: number | null
  lines_added: number
  lines_removed: number

  /** True only while the latest re-scan of a throwaway copy passed every check. */
  validated: boolean
  /** The latest validation, whatever state it is in. Null if never checked. */
  validation: PatchValidation | null

  model: string | null
  prompt_version: number | null
  explanation_id: number | null

  /** How much tidying the model's answer needed before it was usable code. */
  fences_stripped: boolean
  gutters_stripped: number
  /** True when the replacement had to be shifted back to the file's indentation. */
  reindented: boolean

  /**
   * What the model returned when a proposal was refused.
   *
   * Shown behind a disclosure on a failure. "The change mostly deletes code"
   * is a verdict, and a developer is entitled to see what it was passed on —
   * especially since that verdict is sometimes wrong about a correct fix.
   * Null on success, where the diff is the answer.
   */
  rejected_code: string | null
  temperature: number | null

  duration_ms: number | null
  prompt_tokens: number | null
  completion_tokens: number | null
  error_message: string | null
  created_at: string
  finished_at: string | null
}

export type DiffLineKind = 'added' | 'removed' | 'context' | 'meta'

export interface DiffLine {
  kind: DiffLineKind
  text: string
}

/**
 * Split a unified diff into lines the UI can colour.
 *
 * Classification only — this never interprets hunk headers or reconstructs
 * anything. The diff came from the server's `difflib`, and the renderer's only
 * job is to show it, so a malformed line falls through to 'context' and is
 * displayed rather than acted upon.
 */
export function parseDiff(diff: string): DiffLine[] {
  return diff
    .split('\n')
    .filter((line, index, all) => !(line === '' && index === all.length - 1))
    .map((text) => ({ kind: classify(text), text }))
}

function classify(line: string): DiffLineKind {
  // Order matters: '+++' and '---' start with the same characters as changed
  // lines, and colouring them green and red is how a one-line fix comes to
  // look like a two-line one.
  if (line.startsWith('+++') || line.startsWith('---') || line.startsWith('@@')) return 'meta'
  if (line.startsWith('+')) return 'added'
  if (line.startsWith('-')) return 'removed'
  return 'context'
}

/**
 * Where a proposal stands, as one word the panel can switch on.
 *
 * 'undetermined' is deliberately separate from 'rejected'. A check that could
 * not run has not found anything wrong with the change, and the panel must not
 * say that it did.
 */
export type ValidationState = 'unchecked' | 'checking' | 'validated' | 'rejected' | 'undetermined'

export function validationState(patch: Patch): ValidationState {
  const validation = patch.validation
  if (validation === null) return 'unchecked'
  if (ACTIVE_VALIDATION_STATUSES.includes(validation.status)) return 'checking'
  if (validation.status === 'REJECTED') return 'rejected'
  if (validation.status === 'FAILED') return 'undetermined'
  // PASSED alone is not enough: the server's own verdict has to agree. If the
  // two ever disagree, the cautious reading wins.
  return patch.validated ? 'validated' : 'undetermined'
}

/** True while something is still in flight and the panel should keep polling. */
export function isSettling(patch: Patch): boolean {
  return ACTIVE_PATCH_STATUSES.includes(patch.status) || validationState(patch) === 'checking'
}
