/** Mirrors backend/app/schemas/patch.py */

export type PatchStatus = 'QUEUED' | 'RUNNING' | 'PROPOSED' | 'FAILED'

/** Still working — the UI polls while one of these is true. */
export const ACTIVE_PATCH_STATUSES: PatchStatus[] = ['QUEUED', 'RUNNING']

/**
 * A proposed change to the code a finding points at.
 *
 * Note what is absent: there is no 'APPLIED', and `validated` is always false
 * in this phase. Nothing here has been run, tested, or re-scanned — the type
 * is deliberately unable to claim otherwise.
 */
export interface Patch {
  id: number
  finding_id: number
  status: PatchStatus
  attempts: number

  /** A unified diff, generated by the server from before/after — not by the model. */
  diff: string | null
  rationale: string | null
  file_path: string | null
  first_line: number | null
  last_line: number | null
  lines_added: number
  lines_removed: number

  /** Always false until Phase 11 applies a patch to a copy and re-scans it. */
  validated: boolean

  model: string | null
  prompt_version: number | null
  explanation_id: number | null

  /** How much tidying the model's answer needed before it was usable code. */
  fences_stripped: boolean
  gutters_stripped: number

  duration_ms: number | null
  prompt_tokens: number | null
  completion_tokens: number | null
  error_message: string | null
  created_at: string
  finished_at: string | null
}

export type DiffLineKind = 'added' | 'removed' | 'context' | 'meta'

export interface DiffLine {
  kind: DiffLineKind
  text: string
}

/**
 * Split a unified diff into lines the UI can colour.
 *
 * Classification only — this never interprets hunk headers or reconstructs
 * anything. The diff came from the server's `difflib`, and the renderer's only
 * job is to show it, so a malformed line falls through to 'context' and is
 * displayed rather than acted upon.
 */
export function parseDiff(diff: string): DiffLine[] {
  return diff
    .split('\n')
    .filter((line, index, all) => !(line === '' && index === all.length - 1))
    .map((text) => ({ kind: classify(text), text }))
}

function classify(line: string): DiffLineKind {
  // Order matters: '+++' and '---' start with the same characters as changed
  // lines, and colouring them green and red is how a one-line fix comes to
  // look like a two-line one.
  if (line.startsWith('+++') || line.startsWith('---') || line.startsWith('@@')) return 'meta'
  if (line.startsWith('+')) return 'added'
  if (line.startsWith('-')) return 'removed'
  return 'context'
}
