"""users: timezone-aware timestamps, DB defaults, naming convention

Autogenerated, then reviewed and adjusted by hand:

* ``created_at`` / ``updated_at``: ``TIMESTAMP`` -> ``TIMESTAMPTZ`` with
  ``DEFAULT now()``. Existing values were written with ``datetime.utcnow()``
  (naive UTC), so the conversion uses ``AT TIME ZONE 'UTC'``. Without it
  PostgreSQL would interpret them in the server's local time zone
  (e.g. Asia/Kolkata) and silently shift them by +05:30.
* ``is_active``: ``DEFAULT true`` at database level.
* Drops redundant ``ix_users_id`` (the primary key is already indexed).
* Renames ``users_pkey`` -> ``pk_users`` to match the ``Base`` naming convention.
  Conditional: databases created *before* the convention existed have
  ``users_pkey``; fresh databases already get ``pk_users`` from the first
  migration, because Alembic applies the metadata naming convention there too.

Revision ID: 48095f0985ad
Revises: 453fd78e5b07
Create Date: 2026-09-17 16:01:57.920153
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "48095f0985ad"
down_revision: str | Sequence[str] | None = "453fd78e5b07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TIMESTAMP_COLUMNS = ("created_at", "updated_at")


# Rename the users primary key only if it currently has the old name.
RENAME_PK_UP = """
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint
               WHERE conname = 'users_pkey' AND conrelid = 'users'::regclass) THEN
        ALTER TABLE users RENAME CONSTRAINT users_pkey TO pk_users;
    END IF;
END $$;
"""

RENAME_PK_DOWN = """
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint
               WHERE conname = 'pk_users' AND conrelid = 'users'::regclass) THEN
        ALTER TABLE users RENAME CONSTRAINT pk_users TO users_pkey;
    END IF;
END $$;
"""


def upgrade() -> None:
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    for column in TIMESTAMP_COLUMNS:
        op.alter_column(
            "users",
            column,
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            existing_nullable=False,
            postgresql_using=f"{column} AT TIME ZONE 'UTC'",
        )
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.execute(RENAME_PK_UP)


def downgrade() -> None:
    op.execute(RENAME_PK_DOWN)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    for column in reversed(TIMESTAMP_COLUMNS):
        op.alter_column(
            "users",
            column,
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            server_default=None,
            existing_nullable=False,
            postgresql_using=f"{column} AT TIME ZONE 'UTC'",
        )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
