"""projects owned by users

Autogenerated and reviewed; no changes were needed. Points worth noting:

* ``owner_id`` is ``ON DELETE CASCADE``: deleting a user removes their
  projects rather than leaving rows nobody can reach.
* ``uq_projects_owner_id_name`` makes a project name unique *per owner*, not
  globally — two users may both have a project called "SecureBank".
* ``ix_projects_owner_id`` supports the query every project endpoint runs:
  "the projects belonging to this user".

Revision ID: 5e575e845395
Revises: 66e5151881d9
Create Date: 2026-09-25
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5e575e845395"
down_revision: str | Sequence[str] | None = "66e5151881d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.String(length=500), nullable=True),
        sa.Column("default_branch", sa.String(length=100), server_default="main", nullable=False),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("owner_id", "name", name="uq_projects_owner_id_name"),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
