"""Reading the piece of code a finding points at, and splicing a fix back in.

The central decision of Phase 10 lives here: **the model is never asked to
produce a diff.**

Asking a 7B model for a unified diff means asking it to count lines and compute
`@@ -12,7 +12,8 @@` headers. Models are bad at arithmetic and worse at it under
a format constraint, so a meaningful share of answers come back as diffs that
look right and do not apply. Worse, the failures are silent: a hunk header off
by one produces a patch that applies cleanly to the wrong place.

So the split is: the model does the part it is good at — write this code
differently — and this module does the part a computer is good at, which is
knowing which lines those were and what the file looks like afterwards. The diff
is then generated by `difflib` from the before and after, and is correct by
construction.

Nothing here writes to the workspace. A proposal is text until Phase 11.
"""

from dataclasses import dataclass
from pathlib import Path

# How much unchanged code the model sees around the finding. Enough to know
# what the surrounding function is doing and what names are in scope; small
# enough that a CPU generation stays in tens of seconds rather than minutes.
CONTEXT_LINES = 6

# A file this project would not have analysed in the first place, and a shape
# that makes the prompt useless anyway.
MAX_FILE_LINES = 20_000
MAX_LINE_CHARS = 2_000


class RegionError(RuntimeError):
    """The code a finding points at could not be read. Always actionable."""


@dataclass(frozen=True)
class Region:
    """The slice of a file that a proposal is allowed to change."""

    path: Path
    # 1-based, inclusive, as a person reads them and as the UI shows them.
    first_line: int
    last_line: int
    lines: list[str]
    # The whole file, so the patched version can be assembled and diffed.
    file_lines: list[str]

    @property
    def text(self) -> str:
        return "".join(self.lines)

    def numbered(self) -> str:
        """The region with line numbers, for the prompt.

        Numbers are shown so the model can talk about the code, and are
        deliberately *not* asked for back: it returns the replacement text only.
        """
        return "".join(
            f"{number:>5} | {line}" for number, line in enumerate(self.lines, start=self.first_line)
        )


def read_region(
    workspace: Path, file_path: str, line_start: int, line_end: int, *, context: int = CONTEXT_LINES
) -> Region:
    """Read the lines around a finding, from inside the workspace only.

    The containment check is the same one Phase 4 applies to archive members,
    for the same reason: ``file_path`` came out of a database row that was built
    from a repository somebody else uploaded, and a stored ``../../etc/passwd``
    would otherwise be read and handed to a model.
    """
    root = workspace.resolve()
    target = (root / file_path).resolve()
    if not target.is_relative_to(root):
        raise RegionError("That finding points outside its repository workspace.")
    if not target.is_file():
        raise RegionError(
            "The file this finding refers to is no longer in the stored copy of the repository."
        )

    try:
        # newline="" disables universal-newline translation. Without it Python
        # silently turns every CRLF into LF on the way in, `splice` has nothing
        # left to preserve, and the diff is generated against content that does
        # not match the bytes on disk — so `git apply` rejects it on exactly the
        # Windows checkouts this project is developed on.
        with target.open(encoding="utf-8", errors="replace", newline="") as handle:
            content = handle.read()
    except OSError as exc:
        raise RegionError("The file this finding refers to could not be read.") from exc

    file_lines = content.splitlines(keepends=True)
    if not file_lines:
        raise RegionError("That file is empty.")
    if len(file_lines) > MAX_FILE_LINES:
        raise RegionError("That file is too large to propose a change to.")
    if any(len(line) > MAX_LINE_CHARS for line in file_lines):
        # Minified or generated. A patch here would be unreviewable even if the
        # model got it right.
        raise RegionError("That file has lines too long to review a change to.")

    if not 1 <= line_start <= len(file_lines):
        raise RegionError(
            "This finding's line is outside the file, so the stored copy has changed since it "
            "was found. Scan again first."
        )

    first = max(1, line_start - context)
    last = min(len(file_lines), max(line_end, line_start) + context)
    return Region(
        path=target,
        first_line=first,
        last_line=last,
        lines=file_lines[first - 1 : last],
        file_lines=file_lines,
    )


def splice(region: Region, replacement: str) -> list[str]:
    """Return the whole file with the region replaced.

    Line endings are taken from the file rather than from the model. A model
    that answers with `\\n` would otherwise convert a CRLF file wholesale, and
    the diff would be every line in it — technically a correct patch, and
    useless to review.
    """
    ending = _dominant_ending(region.file_lines)
    body = replacement.replace("\r\n", "\n").replace("\r", "\n")
    new_lines = [line + ending for line in body.split("\n")]

    # `split` leaves a trailing empty element for text ending in a newline.
    if new_lines and new_lines[-1] == ending:
        new_lines.pop()

    # Keep the file's final-newline convention: adding or removing one shows up
    # as a change to a line nobody edited.
    replaces_the_last_line = region.last_line == len(region.file_lines)
    file_ends_without_newline = not region.file_lines[-1].endswith(("\n", "\r"))
    if new_lines and replaces_the_last_line and file_ends_without_newline:
        new_lines[-1] = new_lines[-1].rstrip("\r\n")

    return (
        region.file_lines[: region.first_line - 1]
        + new_lines
        + region.file_lines[region.last_line :]
    )


def _dominant_ending(lines: list[str]) -> str:
    crlf = sum(1 for line in lines if line.endswith("\r\n"))
    return "\r\n" if crlf > len(lines) / 2 else "\n"


__all__ = [
    "CONTEXT_LINES",
    "MAX_FILE_LINES",
    "MAX_LINE_CHARS",
    "Region",
    "RegionError",
    "read_region",
    "splice",
]
