"""Reading the piece of code a finding points at, and splicing a fix back in.

The central decision of Phase 10 lives here: **the model is never asked to
produce a diff.**

Asking a 7B model for a unified diff means asking it to count lines and compute
`@@ -12,7 +12,8 @@` headers. Models are bad at arithmetic and worse at it under
a format constraint, so a meaningful share of answers come back as diffs that
look right and do not apply. Worse, the failures are silent: a hunk header off
by one produces a patch that applies cleanly to the wrong place.

So the split is: the model does the part it is good at — write this code
differently — and this module does the part a computer is good at, which is
knowing which lines those were and what the file looks like afterwards. The diff
is then generated by `difflib` from the before and after, and is correct by
construction.

Nothing here writes to the workspace. A proposal is text until Phase 11.
"""

from dataclasses import dataclass
from pathlib import Path

# How much unchanged code the model sees around the finding. Enough to know
# what the surrounding function is doing and what names are in scope; small
# enough that a CPU generation stays in tens of seconds rather than minutes.
CONTEXT_LINES = 6

# A file this project would not have analysed in the first place, and a shape
# that makes the prompt useless anyway.
MAX_FILE_LINES = 20_000
MAX_LINE_CHARS = 2_000


class RegionError(RuntimeError):
    """The code a finding points at could not be read. Always actionable."""


#: Markers that fence off the replaceable lines in the prompt. Deliberately
#: ugly and unlikely to occur in real code, so the model cannot mistake one for
#: part of the program.
REPLACE_START = ">>>>>> REPLACE THESE LINES"
REPLACE_END = "<<<<<< END OF LINES TO REPLACE"


@dataclass(frozen=True)
class Region:
    """The lines a proposal may change, and the code around them.

    The distinction between the two is the whole point of this class, and it
    was learned the expensive way. The first version handed the model the
    finding's line *plus six lines either side* and asked for a replacement of
    all of it. Small models do not do that: asked to fix one line, they return
    one line. That answer then looks like a proposal to delete the other twelve,
    and the deletion check — correctly, by its own lights — threw away a
    perfectly good fix.

    So context is now shown and never asked for. The model sees enough to know
    what is in scope and is asked to rewrite only the lines the finding points
    at, which is the question it can actually answer.
    """

    path: Path
    # The replaceable span: the finding's own lines. 1-based, inclusive, as a
    # person reads them and as the UI shows them.
    first_line: int
    last_line: int
    lines: list[str]
    # Shown to the model, never replaced by it.
    context_before: list[str]
    context_after: list[str]
    # The whole file, so the patched version can be assembled and diffed.
    file_lines: list[str]

    @property
    def text(self) -> str:
        """Just the replaceable lines."""
        return "".join(self.lines)

    @property
    def window_first_line(self) -> int:
        return self.first_line - len(self.context_before)

    @property
    def window_last_line(self) -> int:
        return self.last_line + len(self.context_after)

    def numbered(self) -> str:
        """Everything shown to the model, with the replaceable part fenced off.

        Line numbers are shown so the model can talk about the code, and are
        deliberately *not* asked for back — the contract strips them if they
        come anyway.
        """
        out: list[str] = []
        number = self.window_first_line
        for line in self.context_before:
            out.append(f"{number:>5} | {line}")
            number += 1
        out.append(f"{REPLACE_START} ({self.first_line} to {self.last_line})\n")
        for line in self.lines:
            out.append(f"{number:>5} | {line}")
            number += 1
        out.append(f"{REPLACE_END}\n")
        for line in self.context_after:
            out.append(f"{number:>5} | {line}")
            number += 1
        return "".join(out)


def read_region(
    workspace: Path, file_path: str, line_start: int, line_end: int, *, context: int = CONTEXT_LINES
) -> Region:
    """Read the lines around a finding, from inside the workspace only.

    The containment check is the same one Phase 4 applies to archive members,
    for the same reason: ``file_path`` came out of a database row that was built
    from a repository somebody else uploaded, and a stored ``../../etc/passwd``
    would otherwise be read and handed to a model.
    """
    root = workspace.resolve()
    target = (root / file_path).resolve()
    if not target.is_relative_to(root):
        raise RegionError("That finding points outside its repository workspace.")
    if not target.is_file():
        raise RegionError(
            "The file this finding refers to is no longer in the stored copy of the repository."
        )

    try:
        # newline="" disables universal-newline translation. Without it Python
        # silently turns every CRLF into LF on the way in, `splice` has nothing
        # left to preserve, and the diff is generated against content that does
        # not match the bytes on disk — so `git apply` rejects it on exactly the
        # Windows checkouts this project is developed on.
        with target.open(encoding="utf-8", errors="replace", newline="") as handle:
            content = handle.read()
    except OSError as exc:
        raise RegionError("The file this finding refers to could not be read.") from exc

    file_lines = content.splitlines(keepends=True)
    if not file_lines:
        raise RegionError("That file is empty.")
    if len(file_lines) > MAX_FILE_LINES:
        raise RegionError("That file is too large to propose a change to.")
    if any(len(line) > MAX_LINE_CHARS for line in file_lines):
        # Minified or generated. A patch here would be unreviewable even if the
        # model got it right.
        raise RegionError("That file has lines too long to review a change to.")

    if not 1 <= line_start <= len(file_lines):
        raise RegionError(
            "This finding's line is outside the file, so the stored copy has changed since it "
            "was found. Scan again first."
        )

    # The replaceable span is the finding's own lines, and nothing more. A
    # finding whose end line has drifted past the end of the file is clamped
    # rather than refused: the start line is what the drift check verifies.
    first = line_start
    last = min(len(file_lines), max(line_end, line_start))
    return Region(
        path=target,
        first_line=first,
        last_line=last,
        lines=file_lines[first - 1 : last],
        context_before=file_lines[max(0, first - 1 - context) : first - 1],
        context_after=file_lines[last : last + context],
        file_lines=file_lines,
    )


def reindent(replacement: str, original: list[str]) -> tuple[str, bool]:
    """Put the replacement back at the indentation of the code it replaces.

    Models lose leading whitespace. Asked to fix a line eight spaces deep, a
    7B model returns the corrected line flush against the margin — it answered
    the question and dropped the formatting, which was observed on the very
    first Java proposal this project generated.

    Left alone that is cosmetic in Java and fatal in Python: the patched file
    does not parse, ``check_syntax`` refuses it, and the developer is told
    their correct fix "does not parse as Python".

    Indentation is arithmetic, so the server does it rather than asking the
    model to. The whole block is shifted by the difference between the
    original's indent and the model's, which preserves the relative
    indentation *inside* the replacement — a returned if/else keeps its shape.

    Nothing is done when the model already matched, and nothing is done when
    the replacement is deeper than the original on purpose.
    """
    lines = replacement.split("\n")
    first_code = next((line for line in lines if line.strip()), None)
    if first_code is None or not original:
        return replacement, False

    wanted = _leading_space(original[0])
    got = _leading_space(first_code)
    if wanted == got:
        return replacement, False

    shifted: list[str] = []
    for line in lines:
        if not line.strip():
            shifted.append("")  # never indent a blank line
        elif line.startswith(got):
            shifted.append(wanted + line[len(got) :])
        else:
            # Less indented than the block's own first line. Rare, and not
            # something to guess at: leave it and let the syntax check judge.
            shifted.append(line)
    return "\n".join(shifted), True


def _leading_space(line: str) -> str:
    return line[: len(line) - len(line.lstrip())]


def splice(region: Region, replacement: str) -> list[str]:
    """Return the whole file with the region replaced.

    Line endings are taken from the file rather than from the model. A model
    that answers with `\\n` would otherwise convert a CRLF file wholesale, and
    the diff would be every line in it — technically a correct patch, and
    useless to review.
    """
    ending = _dominant_ending(region.file_lines)
    body = replacement.replace("\r\n", "\n").replace("\r", "\n")
    new_lines = [line + ending for line in body.split("\n")]

    # `split` leaves a trailing empty element for text ending in a newline.
    if new_lines and new_lines[-1] == ending:
        new_lines.pop()

    # Keep the file's final-newline convention: adding or removing one shows up
    # as a change to a line nobody edited.
    replaces_the_last_line = region.last_line == len(region.file_lines)
    file_ends_without_newline = not region.file_lines[-1].endswith(("\n", "\r"))
    if new_lines and replaces_the_last_line and file_ends_without_newline:
        new_lines[-1] = new_lines[-1].rstrip("\r\n")

    return (
        region.file_lines[: region.first_line - 1]
        + new_lines
        + region.file_lines[region.last_line :]
    )


def _dominant_ending(lines: list[str]) -> str:
    crlf = sum(1 for line in lines if line.endswith("\r\n"))
    return "\r\n" if crlf > len(lines) / 2 else "\n"


__all__ = [
    "CONTEXT_LINES",
    "MAX_FILE_LINES",
    "MAX_LINE_CHARS",
    "Region",
    "RegionError",
    "read_region",
    "reindent",
    "splice",
]
