import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'

import { ErrorState } from '../components/ErrorState'
import { LoadingState } from '../components/LoadingState'
import { reportService } from '../services/api'
import { ApiError, toApiError } from '../services/apiClient'
import type { ReportExport, ReportFormat } from '../types/report'
import { REPORT_FORMATS, REPORT_FORMAT_INFO, safeFilename } from '../types/report'
import { saveTextFile } from '../utils/download'

type State =
  | { status: 'loading' }
  | { status: 'ready'; preview: ReportExport }
  | { status: 'error'; error: ApiError }

/**
 * A repository's report: a preview, and the same document in four formats.
 *
 * The report is written by the API, once, and this page only shows it. The
 * preview is the HTML export inside an `<iframe sandbox>` with no permissions
 * at all — no scripts, no forms, no same-origin access — because the document
 * contains text from the scanned repository. The API escapes all of it; the
 * sandbox is there for the day that is not enough.
 */
export function ReportPage() {
  const { repositoryId } = useParams()
  const navigate = useNavigate()
  const id = Number(repositoryId)
  const valid = Number.isInteger(id) && id > 0

  const [state, setState] = useState<State>({ status: 'loading' })
  const [attempt, setAttempt] = useState(0)
  const [busy, setBusy] = useState<ReportFormat | null>(null)
  const [downloadError, setDownloadError] = useState<ApiError | null>(null)

  useEffect(() => {
    if (!valid) return
    const controller = new AbortController()
    reportService
      .export(id, 'html', controller.signal)
      .then((preview) => {
        if (!controller.signal.aborted) setState({ status: 'ready', preview })
      })
      .catch((caught: unknown) => {
        if (controller.signal.aborted) return
        setState({ status: 'error', error: toApiError(caught) })
      })
    return () => controller.abort()
  }, [id, valid, attempt])

  const reload = useCallback(() => {
    setState({ status: 'loading' })
    setAttempt((value) => value + 1)
  }, [])

  const download = useCallback(
    async (format: ReportFormat, preview: ReportExport) => {
      setDownloadError(null)
      setBusy(format)
      try {
        // The preview is already the HTML document: save what is on screen
        // rather than asking for a second one that could differ.
        const file = format === 'html' ? preview : await reportService.export(id, format)
        saveTextFile(safeFilename(file.filename, format), file.content, file.media_type)
      } catch (caught: unknown) {
        setDownloadError(toApiError(caught))
      } finally {
        setBusy(null)
      }
    },
    [id],
  )

  if (!valid) {
    return (
      <section className="page">
        <h1>Report not found</h1>
        <p className="page__subtitle">That address does not point at a repository.</p>
        <p className="page__back">
          <Link className="link" to="/projects">
            Back to projects
          </Link>
        </p>
      </section>
    )
  }

  const notScanned = state.status === 'error' && state.error.code === 'REPORT_NOT_AVAILABLE'

  return (
    <section className="page" aria-labelledby="report-title">
      <div className="page__header">
        <div>
          <p className="page__breadcrumb">
            <button type="button" className="link-button" onClick={() => navigate(-1)}>
              ← Back
            </button>
          </p>
          <h1 id="report-title">Security report</h1>
          <p className="page__subtitle">
            Written from the last completed scan. Nothing here is generated by a model.
          </p>
        </div>
      </div>

      {state.status === 'loading' && <LoadingState label="Writing the report…" />}

      {state.status === 'error' && (
        <ErrorState
          title={notScanned ? 'There is nothing to report yet' : 'Could not write the report'}
          message={state.error.message}
          code={state.error.code}
          requestId={state.error.requestId}
          onRetry={notScanned ? undefined : reload}
        />
      )}

      {state.status === 'ready' && (
        <>
          <div className="panel report__downloads">
            <h2 className="report__heading">Download</h2>
            <ul className="report__formats">
              {REPORT_FORMATS.map((format) => (
                <li key={format}>
                  <button
                    type="button"
                    className="button button--small"
                    onClick={() => void download(format, state.preview)}
                    disabled={busy !== null}
                  >
                    {busy === format ? 'Preparing…' : REPORT_FORMAT_INFO[format].label}
                  </button>
                  <span className="report__purpose">{REPORT_FORMAT_INFO[format].purpose}</span>
                </li>
              ))}
            </ul>
            <p className="report__note">
              For a PDF, download the HTML file, open it and print it. Each download is recorded in
              the audit log.
            </p>
            {downloadError && (
              <p className="repository-card__error" role="alert">
                {downloadError.message}
              </p>
            )}
          </div>

          <iframe
            className="report__preview"
            title="Report preview"
            sandbox=""
            referrerPolicy="no-referrer"
            srcDoc={state.preview.content}
          />
        </>
      )}
    </section>
  )
}
